=== lucke-01/duckacademy-integrations-course/soap/xml-theory/countries.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://duckacademy.nl/country"
            xmlns:people="http://duckacademy.nl/people"
           targetNamespace="http://duckacademy.nl/country" elementFormDefault="qualified">
    <xs:import namespace="http://duckacademy.nl/people" schemaLocation="people.xsd"/>
    <xs:element name="getCountryRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="getCountryResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="country" type="tns:country"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="country">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="name" type="xs:string"/>
            <xs:element name="population" type="xs:int"/>
            <xs:element name="capital" type="xs:string"/>
            <xs:element name="currency" type="tns:currency"/>
            <xs:element name="president" type="people:person"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="currency">
        <xs:restriction base="xs:string">
            <xs:enumeration value="GBP"/>
            <xs:enumeration value="EUR"/>
            <xs:enumeration value="PLN"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== lucke-01/duckacademy-integrations-course/soap/xml-theory/country.xml
<?xml version="1.0" encoding="UTF-8" ?>
<getCountryResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xmlns:countries="http://duckacademy.nl/country"
                    xmlns:people="http://duckacademy.nl/people"
                    xmlns="http://duckacademy.nl/country"
                    xsi:schemaLocation="http://duckacademy.nl/country countries.xsd
                          http://duckacademy.nl/people people.xsd">
    <countries:country>
        <countries:name>Spain</countries:name>
        <countries:population>200</countries:population>
        <countries:capital>Madrid</countries:capital>
        <countries:currency>GBP</countries:currency>
        <countries:president>
            <people:name>adsf</people:name>
            <people:lastName>asdf</people:lastName>
        </countries:president>
    </countries:country>
</getCountryResponse>
